name: server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.0
  postgres: ^3.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgresql2: any
dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
